# query steps
GET http://127.0.0.1:7001/steps

# custom query steps
POST http://127.0.0.1:7001/steps
Content-Type: application/json
x-csrf-token: up3ZfEgMyZ1aVDiOZbmVjQwr

{
  "pageSize": 10,
  "pageNum": 1
}

# check day record
POST http://127.0.0.1:7001/steps/check
Content-Type: application/json
x-csrf-token: up3ZfEgMyZ1aVDiOZbmVjQwr

{
  "date": "2020-04-18",
  "name": "Jason"
}

PUT http://127.0.0.1:7001/steps
Content-Type: application/json
x-csrf-token: up3ZfEgMyZ1aVDiOZbmVjQwr

{
  "date": "2020-04-17",
  "name": "Jason",
  "steps": 13000
}
