POST http://127.0.0.1:7001/gains/check
Content-Type: application/json
x-csrf-token: up3ZfEgMyZ1aVDiOZbmVjQwr

{
  "date": "2020-03-29",
  "name": "Jason",
  "channel": "Alipay"
}

GET http://127.0.0.1:7001/todolist

PUT http://127.0.0.1:7001/todolist
Content-Type: application/json
x-csrf-token: up3ZfEgMyZ1aVDiOZbmVjQwr

{
  "title": "特殊快件中转/派件查询条件托寄物改为托寄物类型",
  "description": "特殊快件中转/派件查询条件托寄物改为托寄物类型",
  "date": "2020-04-01",
  "status": 2
}

POST http://127.0.0.1:7001/todolist/2
Content-Type: application/json
x-csrf-token: up3ZfEgMyZ1aVDiOZbmVjQwr

{
  "status": 2
}

POST http://127.0.0.1:7001/todolist
Content-Type: application/json
x-csrf-token: up3ZfEgMyZ1aVDiOZbmVjQwr

{
  "status": 2
}
